# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f95f56921a88104a38b1a4ec5ee2dea"
name = "timer-pro-app"
application_url = "https://lender-agriculture-medical-met.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://lender-agriculture-medical-met.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://lender-agriculture-medical-met.trycloudflare.com/api/proxy"
subpath = "timer-pro"
prefix = "apps"
